tap "mongodb/brew"
brew "asdf"
brew "bat"
brew "curl"
brew "docker", link: false
brew "fzf"
brew "gh"
brew "git"
brew "jq"
brew "k9s"
brew "kube-ps1"
brew "kubectx"
brew "kubie"
brew "pyenv"
brew "ripgrep"
brew "tmux"
brew "tree"
brew "wget"
brew "yq"
brew "zsh"
cask "google-cloud-sdk", args: { appdir: "/Applications" }
cask "miro"
cask "visual-studio-code", args: { appdir: "/Applications" }
